accountId: "276028776269"
region: ap-northeast-2

image:
  repository: amazon/cloudwatch-agent
  tag: 1.247350.0b251780
  pullPolicy: IfNotPresent

clusterName: jarvis-ap-northeast-2

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi

serviceAccount:
  create: true
  extraAnnotations: {}

hostNetwork: false

nodeSelector: {}

tolerations: []

affinity: {}

# For bottlerocket OS (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-troubleshooting.html#ContainerInsights-troubleshooting-bottlerocket)
# containerdSockPath: /run/dockershim.sock 
containerdSockPath: /run/containerd/containerd.sock
