{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-cloudwatch-metrics.serviceAccountName" . }}
  labels:
    {{- include "aws-cloudwatch-metrics.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.accountId }}:role/jarvis-{{ .Values.region }}-cloudwatch-agent
  {{- with .Values.serviceAccount.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
