apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jarvis:full-control
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
